### ISSUE TITLE
Problema ao enviar o cert

### ISSUE THREAD

**Issue by alcmoraes** [msbrogli/santander-cobranca-xml#1]
Oi Marcelo! Tudo bem!?

Cara, tenho um arquivo .pfx e não to conseguindo de jeito maneira exportar pra mandar ele na requisição.

No manual, diz que o arquivo precisa ser um `.cer`, porém tá dando um exception muito louco quando mando assim.

```
Traceback (most recent call last):
  File "boleto.py", line 41, in <module>
    ret1 = get_ticket(data, cert=cert)
  File "/home....santander-cobranca-xml/santander.py", line 27, in get_ticket
    ret = requests.post(url, data=request_xml, cert=cert)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL] PEM lib (_ssl.c:2584)
```

Se eu mando com .pem ambos certificado e private, ele retorna:

```
<?xml version="1.0" ?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
	<soapenv:Body>
		<dlwmin:createResponse xmlns:dlwmin="http://impl.webservice.dl.app.bsbr.altec.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<TicketResponse>
				<message>Error: java.lang.Exception: Access denied: certificate not found</message>
				<retCode>-1</retCode>
			</TicketResponse>
		</dlwmin:createResponse>
	</soapenv:Body>
</soapenv:Envelope>
```

To com receio de estar enviando no formato errado. Quais formatos você usou?

Abraço!

**Comment by emellyaquino** [comment]
Alcmoraes bom dia, tudo bem?
Estou no momento, implementando na empresa que eu trabalho tambem. 
Uma pergunta, você já abriu o teste no santander? Pois eles também precisam abrir um ambiente lá também.

**Comment by alcmoraes** [comment]
Oi @emellyaquino, você então tá dizendo que precisa enviar uma requisição ao Santander para permitir que eu consiga fazer as requests? A princípio só clonei o repo, taquei as certs da minha empresa e tentei fazer a requisição de login.

**Comment by emellyaquino** [comment]
Olá @alcmoraes  .
No momento, estou homologando aqui na empresa que trabalho também. Aqui usamos o ASP Classic.
Cheguei na seguinte situação: fiz a parte do XML, mas para ter algum retorno na mensagem, é necessário habilitar um certificado digital do tipo client. (Ainda estamos tentando descobrir que certificado é esse). SSL common Server não é compativel. O próprio banco nos orientou que, antes de adquirir ou habilitar qualquer certificado, tínhamos que entrar em contato com eles, pois além disso, eles também precisam habilitar o ambiente no próprio Santander. Isso requer dados da conta bancária, cpnj etc etc.

No momento, essa foi a saída que nos deram. Não sei se pra vocês serão do mesmo jeito. Estou exatamente agora passando informações para o Santander poder habilitar nosso ambiente... Qualquer novidade eu digo aqui.

**Comment by alcmoraes** [comment]
Opa! That's great! Valeu pelas informações. Vou entrar em contato com a minha gerente e ver o que ela fala sobre isso então! Qualquer coisa jogo o feedback aqui também.

Gracias!

**Comment by emellyaquino** [comment]
@alcmoraes 
Aqui nesse repositório, tem o manual do santander.
Dê uma olhada na página 3, onde fala sobre certificado digital.
Na página 26, tem um anexo com o Manual Certificado Digital, onde explica algumas coisinhas. 

Espero que consiga aí! 

Abraços

**Comment by alcmoraes** [comment]
@emellyaquino , então, eu já tinha lido o manual e tudo mais, mas como essa questão não era urgente pra mim, acabei deixando ela de lado depois de tentar realizar alguns testes.

Agora depois da tua mensagem, liguei pro Santander e a gerente da minha conta disse que vai pedir pro pessoal da TI ligar pra mim e me guiar em todo o processo.

Te devo um café!

Obrigadão e um ótimo dia!

**Comment by emellyaquino** [comment]
@alcmoraes disponha!
Qualquer novidade, atualiza aqui!

Ótimo dia!

**Comment by phalkao** [comment]
Bom dia, 

Estou tendo a mesma dificuldade do colega alcmoraes, mesmo com o pessoal do Santander tendo liberado o ambiente para a homologação...

Alguém consegui comcluir o processo?

**Comment by emellyaquino** [comment]
Cara, a gente acabou desistindo. O suporte do Santander é horrivel, levavam dias para tirar duvidas simples. 

Optamos por usar uma API do banco Itaú para realizar o registro dos boletos. Apesar de também serem enrolados, o suporte dos caras foi excelente no auxílio da implantação.

**Comment by phalkao** [comment]
Nossa, que pena. O pior é que o cliente já gastou para adquirir o certificado do Serasa, e quer usar a integração via XML, quando ele falou que queria envio de boleto, eu tinha criado as rotinas usando o padrão cnab 240 e 400 aí mudei todo o processo novamente.

De qualquer forma, vou continuar um pouco mais, caso tenha sucesso posto aqui.

Obrigado.

**Comment by emellyaquino** [comment]
Então... 
Com o Itaú, não precisamos adquirir o certificado. Porém, é cobrado uma taxa de 4,10 a cada boleto registrado. Talvez esse valor tenha que ser repassado para o pagador final, sei lá. vai muito da política da empresa também. Mas nos atualize aqui quando obter sucesso :D

**Comment by Gomes343** [comment]
Olá Pessoal! se alguem tiver uma versão atual do Santander Cobrança XML, eu agradeço hahaha

sobre o certificado, precisa ser a chave publica, exportada em codificação X.509 na base 64 em .cer

o suporte do Santander NÃO SOUBE EXPLICAR ISSO, tive que descobrir testando... kk
